name: math-cpp
version: 0.1.0
homepage: https://github.com/morloclib/math-cpp
synopsis: C++ implementations for math functions
description: C++ implementations for math functions
category: math
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.com"
github: https://github.com/morloclib/math-cpp
bug-reports: https://github.com/morloclib/math-cpp
